name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: update-readme-cards
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_STATS }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 7
          EXCLUDE: "jupyter%20notebook"
          AUTO_PUSH: true
          THEME: "transparent"
          ANIMATION: "load"
          DURATION: ""
          NAME: ""
